seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  gradient_clip_val: 1.0
  max_steps: 500000
  # logger:
  #   class_path: lightning.pytorch.loggers.WandbLogger
  #   name: "fstar-premise-retrieval-random"
  #   project: "premise-selection"
  #   log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: NDCG
        mode: max
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: NDCG
        patience: 3
        mode: max
        verbose: true

model:
  model_name: google/byt5-small
  lr: 1e-4
  warmup_steps: 2000
  num_retrieved: 100
  d_embed: 512

data:
  data_path: ../llm_benchmarking/fstar_insights/lemmas_with_premises/saikat_dataset_filtered_premises/initial_data/
  corpus_path: ../llm_benchmarking/fstar_insights/lemmas_with_premises/corpus.json
  import_graph_path: ../llm_benchmarking/fstar_insights/lemmas_with_premises/file_import_graph.json
  num_negatives: 3
  num_in_file_negatives: 1
  batch_size: 32
  eval_batch_size: 128
  max_seq_len: 1024
  num_workers: 4
